import { MainLayout } from './components/main-layout';
import { ChatPage } from './components/chat-page';
/*This is the main app component that is used to render the main layout and the chat page generated by Figma design.*/

export default function App() {
  return (
    <MainLayout>
      <ChatPage />
    </MainLayout>
  );
}